[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)][def]

[def]: https://colab.research.google.com/github/LEE-Sanghoon/MNT2009/blob/main/AI-도미와빙어.ipynb

# **인공지능의 이해 수업시간**


In [1]:
# 도미 데이터
bream_length = [
25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0,
31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0,
35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0
]
bream_weight = [
242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0,
500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0,
700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0
]
# 빙어 데이터
smelt_length = [9.8, 10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
smelt_weight = [6.7, 7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(bream_length, bream_weight)
plt.scatter(smelt_length, smelt_weight)
plt.xlabel('length')
plt.ylabel('weight')
plt.show()

In [3]:
length = bream_length + smelt_length
weight = bream_weight + smelt_weight

fish_data = [ [l, w] for l, w in zip(length, weight)]
fish_target = [1]*35 + [0]*14

! pip3 install scikit-learn

In [5]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
kn.fit(fish_data, fish_target)
kn.score(fish_data, fish_target)

1.0

In [6]:
kn.predict( [[30, 600]])

array([1])

In [7]:
train_input = fish_data[:35]
train_target = fish_target[:35]
test_input = fish_data[35:]
test_target = fish_target[35:]

In [8]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
kn = kn.fit(train_input, train_target)
kn.score(test_input, test_target)

0.0

In [9]:
import numpy as np
input_arr = np.array(fish_data)
target_arr = np.array(fish_target)
index = np.arange(49)
np.random.shuffle(index)
print(index)

[17  1 24 48 31  7 15 21 42 22 29  3  0 19  2 34  6 23  9 43 38 47 30 12
 37 32  8 28 33 14 45  4 27 36 40  5 10 44 46 16 26 41 25 35 18 11 13 20
 39]


In [10]:
train_input = input_arr[index[:35]]
train_target = target_arr[index[:35]]
test_input = input_arr[index[35:]]
test_target = target_arr[index[35:]]

In [11]:
kn = kn.fit(train_input, train_target)
kn.score(test_input, test_target)

1.0

In [12]:
kn.predict(test_input)

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0])

In [13]:
test_target

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0])